version: '3.2'

services:
  ocr:
    container_name: cvyolov5_on_ngx
    image: nginx
    ports:
      - 5000:80
    tty: true
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - ocr-net

networks:
  ocr-net:
  
